// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jogdukxsxjwjhozwfapy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvZ2R1a3hzeGp3amhvendmYXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNDQ0MjAsImV4cCI6MjA2MDgyMDQyMH0.RHtTIpBSTP3jEY4bHq_c76EMnik2fZQ1itdWpI-_cQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);